### ISSUE TITLE
gharraph - Create roughed-in resources

### ISSUE THREAD

**Issue by mdarby** [columbusrb/conclave#1]
Off the top of my head, we'll need:

User
Thread
Post

Thread and Post are pretty bad object names as they'll collide with existing objects. So, let's name the objects:

User
Conversation
Comment

I would want to name "Comment" "Message" in a perfect world, but that would likely collide or get confusing down the road.

The User resource should be created with Devise.

**Comment by DustinFisher** [comment]
We would need categories and then each category can have sub-categories below it.

I am not sure the best way to name or set that up though.

Would you just need a single Category object and the subs fall inside that?

**Comment by mdarby** [comment]
I think we could do something like have "Forum"s inside the app? So it would be that a Forum would have many Conversations, in turn made up of Comments. Is this kind of what you were thinking?

**Comment by abwinkler999** [comment]
So:

Users exist;
Forums exist;
A Forum has many Conversations;
A Conversation has many Comments;
A User has many Comments;
A Comment has only one User.

Does that sum it up?

**Comment by gharraph** [comment]
I did not work with GH Issues before. How will I start assign myself to a task? I did couple of projects with Devise before. I can start the project and integrate Devise with the User resource, if everyone is ok with this?

**Comment by mdarby** [comment]
@abwinkler999: Yes, that sounds about right!
@gharraph: I can assign you to this task if you'd like to take a stab at it?

**Comment by gharraph** [comment]
Would love to, I already started:)

**Comment by theotherzach** [comment]
What are the fundamental differences between a conversation and a comment? Would it make any sense to model all posts as belonging to a user and optionally as a reply to another comment? All parent posts could be defined with a root method. 

Something like this off the top of my head if it were being done with Active Record.

https://gist.github.com/3750269

**Comment by gharraph** [comment]
I think this is a good idea.
a user has many posts
a post has many comments

and we can even nest comments, so users can reply to comment by a comment

Sherief

**Comment by mdarby** [comment]
@theotherzach: A Conversation would just be a container (with a title) for Comments. I think that a Comment should know about it's User (author), and also any replies (which would also be Comments). I dig your gist, what do you think of my comments?

@gharraph: Not sure I follow. How would a Post be different than a Comment? Both are just a blob of content, no?

Also I'd prefer to shy away from using "Post" as a resource name. It'll get super confusing later on.

**Comment by tllucero** [comment]
A comment would either start a conversion or be a reply to a previous comment. Either way, it would belong to a conversation. Question - can a comment or a conversation be edited or deleted?

**Comment by mdarby** [comment]
@tllucero I think editing and/or deleting could be an admin option for the forum? I can see equal pros and cons for both sides. Thoughts?

**Comment by DustinFisher** [comment]
I would say a comment or a conversation can be edited by the owner and by
either an admin/moderator.

**Comment by theotherzach** [comment]
@mdarby I could see post getting confusing, point taken. I also agree that having a specific place for groups of comments to live makes sense. Otherwise we're re-implimenting Twitter.

**Comment by mdarby** [comment]
Having Conversation as a container for many Comments will keep it clean when we need to delete a Conversation. Just do a :dependent => :destroy on the association. Viola, cleanliness :)

**Comment by gharraph** [comment]
@matt: The way I thought about it; is how the user will start conversation?
my original thinking was that a user can post (question, or any interesting
topic) then other users can comment on it.
I don't think a user can start thread (conversation) with a comment?

**Comment by mdarby** [comment]
@gharraph Agreed, but I'm not sure we'd need a whole new resource (ie, Post), just to start a Conversation -- we could just create a Conversation when we create a Comment that is not associated with an existing Conversation, and let's say that the form has a nested attribute field for the new Conversation#title. See where I'm going?

**Comment by gharraph** [comment]
@matt: Ok, sounds good to me. I think this will actually make it simpler.

**Comment by tllucero** [comment]
Definitely start a conversation with a comment and a title.

I would add in topic/subtopic with a similar structure to conversation/comment. This should make it easier to avoid duplicate conversations and find conversations a user might have an interest in. In a gem/generator, might make this optional the way devise makes certain fields optional. Might restrict who can create topics. Presumably any non-banned user can comment.

Would have an ordinal within topic/conversation so that for longer conversations/topics can page at 10/20/50 comments per page. 

I asked about delete because don't want orphan comments. And about edit so that replies refer to the original version of a comment. At this point my head starts to hurt.

Finally, the reason I haven't done some version of this project already. Is there a good spam filter in Ruby? Or that can be referenced in Ruby? The great downfall of fora everywhere is spam.

**Comment by skord** [comment]
@tllucero 

I have a robot killer @ https://github.com/skord/httpbl

There's also https://github.com/ysbaddaden/ruby-akismet for using WordPress' collective anti-spam filters. It works pretty darn well.

**Comment by mdarby** [comment]
@gharraph Any further work toward the other roughed-in resources? Need help?

**Comment by gharraph** [comment]
Sure... I wanted to give opportunity for more contributors. I will create
the Comment resources this weekend.

Sent from my iPhone

On Sep 21, 2012, at 1:55 PM, Matt Darby notifications@github.com wrote:

@gharraph https://github.com/gharraph Any further work toward the other
roughed-in resources? Need help?

—
Reply to this email directly or view it on
GitHubhttps://github.com/columbusrb/conclave/issues/1#issuecomment-8775391.

**Comment by mdarby** [comment]
Eh, I got bored. I've added Forum > Conversation > Comment and related associations and specs.
