### ISSUE TITLE
Create Heroku app

### ISSUE THREAD

**Issue by mdarby** [columbusrb/conclave#10]

**Comment by skord** [comment]
I pushed fe284667334db03363a6dc434dc6dd98e2c544c6 to try and resolve some issues with Heroku deployment, but activeadmin is broken, specifically its assets.

http://dry-ravine-4861.herokuapp.com/

**Comment by skord** [comment]
Moved to http://conclaveapp.herokuapp.com/

Seems to be working ok. If there are no objections to running this on my account, I'll close this in a few days.

**Comment by skord** [comment]
Actually, I don't have a mailer setup. There seem to be a half dozen add-ons for it, anyone have a recommendation for one or the other?

**Comment by skord** [comment]
I got a mailer. Closing this. I'll do my best to keep up with this, it's:

http://conclaveapp.herokuapp.com/
