### ISSUE TITLE
Issues with Comment Reply Preview view

### ISSUE THREAD

**Issue by cashby** [columbusrb/conclave#102]
**Issues with Reply Preview**  
- Edit button does not link to anything
- Gravatar is too large
- Email falls below gravatar
- Time format can be improved
- Preview of comment appears right of gravatar instead of below
- The preview should look more like the published comment will look

**Comment by cashby** [comment]
OK. I guess next time I'll figure out how to include my pull request with the issue.  See issue #103 for the pull request.

**Comment by skord** [comment]
No worries. Pull request should create an issue automagically.
