### ISSUE TITLE
Create AWS S3 bucket for file uploads

### ISSUE THREAD

**Issue by mdarby** [columbusrb/conclave#11]

**Comment by gharraph** [comment]
I'm planing to work on adding the file upload capability to comments. Should I use my own AWS account, or do you have an account setup for this project?

**Comment by skord** [comment]
I suggest the use of foreman's ability to have a .env file that will export things like a AWS key into your environment variables. Add a .gitignore for .env and create a sample.env with the proper keys and values. 

_edit_: layman's terms means that everyone has their own bucket for development and you'd use heroku's tools for production.

**Comment by mdarby** [comment]
Great idea -- and no one has to share their AWS credentials.

**Comment by gharraph** [comment]
This sounds a great idea.  I found good documentation on Heroku on how to it.
Thank you

**Comment by mdarby** [comment]
Could you post a link? I'm unfamiliar myself.

**Comment by skord** [comment]
https://devcenter.heroku.com/articles/procfile

The .env file is what you're looking for, I already have the Procfile setup. 

Suggestion is including a sample.env file with fake credentials and instructions on creating your own. Comes in handy for things like twitter and facebook keys too.

**Comment by gharraph** [comment]
https://devcenter.heroku.com/articles/config-vars

This is the link I was talking about.

**Comment by gharraph** [comment]
@skord Since I will use Paperclip gem, I will have to setup s3_credentials option for has_attached_file method according to the following link:
http://rubydoc.info/gems/paperclip/Paperclip/Storage/S3
How can I use .env file instead? I think your suggestion would work if I'm not using the paperclip gem?

**Comment by gharraph** [comment]
I found the solution. I think this is a perfect:
http://icebergist.com/posts/paperclip-heroku-and-amazon-s3-credentials

**Comment by mdarby** [comment]
Nice find! :)

**Comment by skord** [comment]
I think that the yaml solution as linked there would require your credentials in the repo. You could just use ENV['S3_SECRET'] in the yaml file.

**Comment by gharraph** [comment]
no, I just put the s3.yml in the .gitignore

**Comment by mdarby** [comment]
We will need a s3.yml at some point, and since we're going to eventually wrap this up as a gem/engine, I think its best to do the ENV vars in the s3.yml. This way we can direct the end installer to more easily add their creds. Thoughts?

**Comment by skord** [comment]
For now I would like the ENV's in the yml file, but I think eventually I'd like to have this as a configurable. I've been scratching my head on how to best wrap a GUI around site-wide variables. The view is pretty simple since we have activeadmin, but I'm really bouncing around on how to handle the serialization of that sort of data.

**Comment by gharraph** [comment]
Ok, at this point I can not get Paperclip to work! I have two problems:
first paperclip is passing photos object instead of hash as params:

 "comment"=>{"content"=>"XCCCV", "photo"=>#<ActionDispatch::Http::UploadedFile:0x007fe9ceedbad8 @original_filename="IMG_0607.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"comment[photo]\"; filename=\"IMG_0607.jpg\"\r\nContent-Type: image/jpeg\r\n", @tempfile=#<File:/var/folders/x7/9yzk9fdj6t57b4gcwmhvwpc40000gn/T/RackMultipart20120926-39089-1kxyivc>>}, "commit"=>"Submit Comment", "conversation_id"=>"1"}

in my controller, per documentation of Paperclip I should create my comment with mass assignment like this:
@comment = Comment.new do |c|
      c.conversation = @conversation
      c.content = params[:comment][:content]
      c.user = current_user
    end

as you can see the :content hash does not include the photos attributes. I have my form like this:
= simple_form_for [@conversation, @comment], :html => {:class => 'form-horizontal', :multipart => true} do |f|
  = f.error_notification
  .form-inputs
    = f.input :content, :required => true, :autofocus => true, :label => "Body", :input_html => {:class => "span9"}
    = f.file_field :content, :photo
  .form-actions
    = f.button :submit, "Submit Comment", :class => "btn btn-primary"

ideally (or what I expect) the form should pass params like:
"comment"=>{"content"=>"XCCCV", "photo"=>{"photo_file_name"=> "some_sile_name", "photo_content_type=>"file_type", ......}, "commit"=>"Submit Comment", "conversation_id"=>"1"}

Any idea what I might be doing wrong?

Second, which I guess related to this problem is I keep getting the following error:

ctionController::RoutingError (No route matches [GET] "/images/medium/missing.png"):

**Comment by skord** [comment]
It's looking for the "backup" image in case the actual one doesn't exist.

While doing the form in this manner is pretty easy, meh, file uploads. I'm not entirely familiar with paperclip as I am Carrierwave, but looking at this initially, my guess is that the process is sort of like:
1. Upload the attachment with the form
2. Store the attachment to local tmp storage
3. Perform any sort of thumbnailing/processing on the temp file
4. Upload the kit and kaboodle to S3
5. Persist the comment instance.

The problem with this approach is that the file upload is a process blocker causing poor site performance while uploads are taking place.

The better option, IMHO, is:
1. Configure the form to upload straight to S3
2. Persist the comment instance with a "file processing" attribute set to true
3. Fetch the file from S3 and do your temp work locally in a background worker
4. Upload any thumbnails, etc back to S3
5. Save the Comment instance with the "file processing" attribute set to nil

I've scrounged around for ways to do this with Paperclip, and there are examples such as http://spin.atomicobject.com/2011/10/31/upload-files-directly-to-s3-with-plupload-rails-and-paperclip/. I know there's a Carrierwave gem (https://github.com/dwilkie/carrierwave_direct) that provides functionality to do it this way, but I'm not entirely certain how to go ahead with Paperclip.

The downside of storing direct to S3 is that this will require a worker process like Sidekiq (my recommendation), Resque, or Delayed Job, which in turn requires a bit more infrastructure (although easy with the free tiers of Redis2Go, etc).

**Comment by gharraph** [comment]
@skord  Thank you. I finally got it to work. it took me quite some time! I found that the validations and the way comment params was assigned is the problem. 
now that it works, I see your point above. The file upload process is really slow.
I will try to implement your idea tonight and will let you know

**Comment by skord** [comment]
@gharraph Awesome! This is one of my gripes about Ruby in general. File uploads are the reason Merb was created. The GIL is not your friend... except when it is. I suppose it's kinda like a spouse.

Heroku is simultaneously brilliant, terrible, and weird -- and the extremes of each. I suppose I could use the same descriptions for the Ruby community and extrapolate as to why I fit into it. You'd think taking some bytes from here and putting them there would be simple, but nooooooooo. In the end, all roads lead into the dark black heart of Rack, which is sort of like Mordor, but with a call function. 

Good luck on the direct to S3 thing, can't wait to see your results.

**Comment by rjo1970** [comment]
It seems like something like send-to-S3 or save-to-disk or insert-in-blob-field or toss-in-a-Hash is exactly the kind of implementation detail you don't want to hard-code explicitly.  Can we decouple the implementation from our project?

**Comment by gharraph** [comment]
@rjo1970 I'm not sure which project you are talking about, but if you have any ready-made code, I would be happy to use it. I'm still educating my self on back processes and how I can control them.  so if you done something like this before I would love to see.

**Comment by mdarby** [comment]
I'd say saving-to-s3 is the best route. Most apps I've worked on have a S3 account these days (if they don't they're free and easy). Saving-to-disk rules out Heroku (where most apps are hosted), and "nuh-uh" to insert-in-blob-field route. :)

**Comment by gharraph** [comment]
yes this is the route I'm taking now. I will take skord idea and use Sidekiq as worker process.

**Comment by mdarby** [comment]
I've read through and I don't understand the need for background processing? Paperclip will create thumbnails on the fly and upload directly to S3 out of the box...

**Comment by skord** [comment]
@mdarby try this one on

https://groups.google.com/forum/?fromgroups=#!topic/heroku/UbxjKNswA0Q

Slow uploads kill Unicorns, amongst other things.

**Comment by mdarby** [comment]
Agreed, but if we're only concerned about <= 500KB photos, does it make sense to add the whole background processor overhead / cost?

**Comment by skord** [comment]
@mdarby Exactly. I'd even forgo thumbnailing. Certain images, like animated gifs can have pretty heavy overhead on resize. What if people aren't uploading images? Perhaps whitelist more than images and just have an icon for the mime type?

**Comment by mdarby** [comment]
I think this sounds like an admin option. As an admin I'd want to toggle file uploads et al, and if "on", I'd want to specify a group of tile types; 'images', 'documents', whatever.

**Comment by gharraph** [comment]
We always can validate the content type to regular images only! right now the process of uploading regular images less than 500KB takes 2 to 3 seconds, which is not that bad!

**Comment by rjo1970** [comment]
As a developer,
Given a clone of conclave
I do not want to require having an AWS S3 to get the default tests passing or unicorn flying locally

Not a rant.  Just trying to keep the bar of entry as low as possible.

**Comment by mdarby** [comment]
```
Comment.stub!(:save_attached_files).and_return(true)
```

**Comment by mdarby** [comment]
I've implemented this:

I've added a new model named AdminSettings. It has an entry in `rake db:seed` that populates some default-AWS keys we need values for (ie, the end user's AWS ID, secret, bucket name, etc). The values can easily be updated via ActiveAdmin.

This way, we provide a GUI for the settings and we won't accidentally commit AWS information.

**Comment by skord** [comment]
Sweet. Works well on Heroku after a restart.

**Comment by mdarby** [comment]
Nice.
