### ISSUE TITLE
Needs Favicon/Touch Icons

### ISSUE THREAD

**Issue by skord** [columbusrb/conclave#112]
This could be fun. A Pope hat comes to mind with a big Ruby on it. Ideas?

**Comment by jesscanady** [comment]
:+1: on the Pope Hat / Ruby combo.

**Comment by skord** [comment]
Hrm.

![http://skord.org/i/35008aa3.png](http://skord.org/i/35008aa3.png)

**Comment by skord** [comment]
closed with 1d5143d82fc7d6d93676c8837269380c917785ef

However my skills of an artist are terrible and I'd probably just consider this a place holder
