### ISSUE TITLE
Moving from SQLite to PG in Dev mode.

### ISSUE THREAD

**Issue by skord** [columbusrb/conclave#122]
Is anyone opposed to this?

Reasons for: 
- I'm running some tests and am getting a DB locked message. Boo.
- The scope problems we had earlier.

Reasons against:
- Configuring and running postgres.

Vote? Will close the issue in 24 hours or so if no decision is made. Or if a decision is made.

**Comment by mdarby** [comment]
I'm fine with PG. In fact I use it for dev on all Heroku-targeted projects.

**Comment by skord** [comment]
@mdarby PostgreSQL Club for Rubyists. I'm not only a member, I'm also a client.

**Comment by tllucero** [comment]
Go with pg.
