### ISSUE TITLE
Display Names

### ISSUE THREAD

**Issue by skord** [columbusrb/conclave#125]
If a user isn't socially created, their email is splattered all over the site. I'm guessing a "display name" on sign up would be a good idea as a required field. 

It would probably be a good idea to fit this into User#name. After that, there's the task of going everywhere that their email is referenced directly and change it to User#name for the sake of uniformity.

**Comment by skord** [comment]
working on this now. you could be too if you were here.

**Comment by DVG** [comment]
@skord Are you still working on this?

**Comment by skord** [comment]
About 30 seconds ago I blew away my local changes on this, so no.
