### ISSUE TITLE
Forum option on how to handle edit/deleting Comments

### ISSUE THREAD

**Issue by mdarby** [columbusrb/conclave#17]
An admin of a Forum may choose to allow Comments to be any of the following:
1. Edited at any time
2. Edited until another Comment has been added to the Conversation
3. Deleted at any time
4. Deleted until another Comment has been added to the Conversation

**Comment by tllucero** [comment]
In implementing this for delete, I wouldn't delete the comment, just prevent it from displaying. Reason: to avoid orphan comments.

**Comment by skord** [comment]
[comment removed]

How meta is that?

**Comment by mdarby** [comment]
I would say that if a Comment is hidden we should also hide any replies to that Comment (as they would just be noise at that point)

**Comment by DVG** [comment]
Personally I'd leave the downstream comments still, because I think the end users would start getting confused why their comments are gone, especially since side conversations can pop-up with context independent of the root node

**Comment by mdarby** [comment]
True, I can see that. Let's just flag the Comment and swap out the content with some placeholder.

**Comment by tllucero** [comment]
Good. Placeholder "This comment removed". Long form "This comment removed by moderator/user" :"This comment flagged as spam" with or without timestamp. Have we specified this enough to make working code?

**Comment by DVG** [comment]
I think there's still a fundamental question to be answered about the view of a conversation. The way I see you can do a straight by create_at sort and display all comments in order, or you can do a threaded view like Reddit where comments are organized based off a root node and replies to that node.

The first one is by far simpler

**Comment by mdarby** [comment]
I prefer a straight-line conversation, personally. That's the point of having separate Conversations.

**Comment by tllucero** [comment]
I'd go with straight-line as default, and, if it is implemented, have threaded as a user option. Without threaded, I'm not nearly as concerned about orphan comments, but prefer to design forum thinking about conversation threads.

**Comment by skord** [comment]
Going back to the initial issue, if we're to use a nullification on the comment attributes, we probably have to add the attributes of: deleted:boolean, deleted_at:datetime, and deleted_by:references (to User). 

My best reasoning for using a deleted boolean is to keep the original comment intact in case there's some other reason  an admin or mod needs to go back and change the user's role to banned.

**Comment by mdarby** [comment]
Sounds right to me.

**Comment by skord** [comment]
Hrm. Does one do this as CommentsController#delete or something like CommentsController#erase, or even some other verb that indicates that it's not really gone, such as CommentsController#redact? Opinions?
