### ISSUE TITLE
Conversations should be stickyable and lockable

### ISSUE THREAD

**Issue by skord** [columbusrb/conclave#20]
A conversation should be sticky-able, meaning it is at the top of the list of topical conversations. 

A conversation should also be lockable, where it is still displayed to users, but is closed for additional commenting. 

Of course, these will also require the inverse methods of unsticky and unlock.

**Comment by mdarby** [comment]
+1

**Comment by DVG** [comment]
I'm gonna work on this next

**Comment by skord** [comment]
This also implies that conversations have an order, which currently is the default of the ID. Do we do this as:
1. As comments are added to conversations, they move to the top (updated at or acts_as_list)
2. Conversations are in a fixed order by id/created_at.
3. Allow users to decide whether they sort by option 1 or option 2.

**Comment by DVG** [comment]
Having comment `touch` conversation and sort by updated_at makes the most sense to me.

**Comment by mdarby** [comment]
Yeah, we should show the most recently added-to conversation at the top of the index.

**Comment by tllucero** [comment]
Default two field sort. First by sticky/non-sticky, then by updated_at.

**Comment by DVG** [comment]
I've got this about 90% implemented, working on the last few cukes, will send a PR tonight probably.

**Comment by mdarby** [comment]
Awesome!

**Comment by mdarby** [comment]
Any movement on this @DVG?

**Comment by DVG** [comment]
Still got one scenario to pass. Got distracted this weekend with my bachelor party. Try and finish up tonight

**Comment by mdarby** [comment]
Well, jeez, I guess that's important enough :)

**Comment by DVG** [comment]
So I still haven't gotten a chance to finish this up, and wedding stuff has ramped up like whoa, so I don't think I'm going to get to until I get back on the 25th. So I'm gonna go ahead and try to merge upstream tonight, push my changes to my fork and if someone wants to take over they can.

**Comment by mdarby** [comment]
Added in 9585b37
