### ISSUE TITLE
Unfortunately, a fatal error has occurred !!!!!

### ISSUE THREAD

**Issue by gharraph** [columbusrb/conclave#34]
I have been pulling my hair last two days trying to solve the below error. any help would be really appreciated. This error only occur when i use ruby 1.9.2. it gets initiated when I bundle. When i use 1.9.3, bundle install works fine. One of my friends suggested that my xcode needed to be downgraded from 4.3 to 4.1. I already tried this but still doing the same thing! I'm trying now to upgrade Xcode to 4.5:

Unfortunately, a fatal error has occurred. Please see the Bundler 
troubleshooting documentation at http://bit.ly/bundler-issues. Thanks! 
/Users/gharraph/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': dlopen(/Users/gharraph/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/x86_64-darwin11.4.0/digest/sha1.bundle, 9): Library not loaded: /opt/sm/pkg/versions/openssl/1.0.1c/lib/libcrypto.1.0.0.dylib (LoadError)
  Referenced from: /Users/gharraph/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/x86_64-darwin11.4.0/digest/sha1.bundle
  Reason: image not found - /Users/gharraph/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/x86_64-darwin11.4.0/digest/sha1.bundle
    from /Users/gharraph/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /Users/gharraph/.rvm/gems/ruby-1.9.2-p320@conclave/gems/bundler-1.2.1/lib/bundler/definition.rb:1:in `<top (required)>'
    from /Users/gharraph/.rvm/gems/ruby-1.9.2-p320@conclave/gems/bundler-1.2.1/lib/bundler.rb:144:in`definition'
    from /Users/gharraph/.rvm/gems/ruby-1.9.2-p320@conclave/gems/bundler-1.2.1/lib/bundler/cli.rb:228:in `install'
    from /Users/gharraph/.rvm/gems/ruby-1.9.2-p320@conclave/gems/bundler-1.2.1/lib/bundler/vendor/thor/task.rb:27:in`run'
    from /Users/gharraph/.rvm/gems/ruby-1.9.2-p320@conclave/gems/bundler-1.2.1/lib/bundler/vendor/thor/invocation.rb:120:in `invoke_task'
    from /Users/gharraph/.rvm/gems/ruby-1.9.2-p320@conclave/gems/bundler-1.2.1/lib/bundler/vendor/thor.rb:275:in`dispatch'
    from /Users/gharraph/.rvm/gems/ruby-1.9.2-p320@conclave/gems/bundler-1.2.1/lib/bundler/vendor/thor/base.rb:408:in `start'
    from /Users/gharraph/.rvm/gems/ruby-1.9.2-p320@conclave/gems/bundler-1.2.1/bin/bundle:14:in`block in <top (required)>'
    from /Users/gharraph/.rvm/gems/ruby-1.9.2-p320@conclave/gems/bundler-1.2.1/lib/bundler/friendly_errors.rb:4:in `with_friendly_errors'
    from /Users/gharraph/.rvm/gems/ruby-1.9.2-p320@conclave/gems/bundler-1.2.1/bin/bundle:14:in`<top (required)>'
    from /Users/gharraph/.rvm/gems/ruby-1.9.2-p320@conclave/bin/bundle:19:in `load'
    from /Users/gharraph/.rvm/gems/ruby-1.9.2-p320@conclave/bin/bundle:19:in`<main>'
    from /Users/gharraph/.rvm/gems/ruby-1.9.2-p320@conclave/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/gharraph/.rvm/gems/ruby-1.9.2-p320@conclave/bin/ruby_noexec_wrapper:14:in`<main>'

**Comment by theotherzach** [comment]
Stupid question with a stupid follow up question:

Do we care about 1.9.2 compatibility? If so, when do we start caring about 1.9.2 compatibility? 

Edit: Nevermind; missed the part where 1.9.2 is the official Ruby of the project.

**Comment by DVG** [comment]
Have you tried imploding rvm and starting from scratch? I do that sometimes when my Mac gets fussy like this

**Comment by gharraph** [comment]
I thought we are doing this project with 1.9.2! I got this from the read me
file.

Sent from my iPhone

On Sep 23, 2012, at 1:21 PM, Zach notifications@github.com wrote:

Stupid question with a stupid follow up question:

Do we care about 1.9.2 compatibility? If so, when do we start caring about
1.9.2 compatibility?

—
Reply to this email directly or view it on
GitHubhttps://github.com/columbusrb/conclave/issues/34#issuecomment-8800510.

**Comment by theotherzach** [comment]
Yeah, you should forget the part where I said something right then. 

Look over there!

/smokebomb

**Comment by mdarby** [comment]
Sharrief, have you seen this? http://stackoverflow.com/questions/9000262/persistent-ruby-segfaulting-after-a-clean-install

It seems that you might have to `rvm implode` your 1.9.2 instance, and reinstall with the flags shown.

**Comment by gharraph** [comment]
FINALY! IT WORKED!! YAY. Thank you Matt your the Stackoverflow link was rally useful. I will finally start contributing again. I have a lot of reading to catch up with to know who did what:)

Thank you

**Comment by mdarby** [comment]
Awesome, glad to hear :)
