### ISSUE TITLE
Set up Travis to run JavaScript specs and cukes so we don't have to

### ISSUE THREAD

**Issue by DVG** [columbusrb/conclave#37]

**Comment by mdarby** [comment]
Do you have any pointers on this? There is a `.travis.yml` file that should control this?

**Comment by DVG** [comment]
We need to run xvfb and tell it to use the appropriate scripts

I've done something like this before (this example used mysql):

```
#setup tasks
before_script:
  - mysql -e 'create database myapp_test;'
  - rake db:migrate
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: bundle exec rspec spec
```

I think we would add another cucumber profile called "everything" or something similar and do

```
script:
  - bundle exec rspec spec
  - bundle exec cucumber -p everything
```

**Comment by tgsoverly** [comment]
I actually just did this and will send a pull request in a couple days.
