### ISSUE TITLE
Page visitors shouldn't be able to create comments or conversations unless signed in

### ISSUE THREAD

**Issue by Bestra** [columbusrb/conclave#38]

**Comment by Bestra** [comment]
What do you guys think? Should a visitor simply be redirected to the signin page upon trying to add a new conversation/comment, or should they see something different than what a signed-in user sees?

**Comment by DVG** [comment]
I would think that you'd hide the New Conversation and Reply buttons, hide the quick reply form if the user doesn't have the adequate permissions, and if they try to access the routes directly redirect them to the login form.

**Comment by mdarby** [comment]
+1 DVG. Show the content, but you must be logged in to participate.
