### ISSUE TITLE
A Comment should know if it is a reply to an existing Comment.

### ISSUE THREAD

**Issue by mdarby** [columbusrb/conclave#4]

**Comment by Bestra** [comment]
Call it a naive question, but is this kind of thing commonly managed through the model association (I'm assuming a comment has_many replies) or is it better to additionally set some kind of is_reply_to attribute when the reply comment is first created?

**Comment by gharraph** [comment]
@Chris Westra: I think we can consider nested comments. Please check these
links for more explanation:

http://kconrails.com/2010/10/23/nested-comments-in-ruby-on-rails-1-models/

http://kconrails.com/2011/01/26/nested-comments-in-ruby-on-rails-controllers-and-views/

**Comment by Bestra** [comment]
Oh for sure.  And in retrospect, both of my suggestions are essentially the same thing.  The schema for Comment is going to have an id for the comment and an id for the comment's parent either way.
