### ISSUE TITLE
Layout Mockup

### ISSUE THREAD

**Issue by DVG** [columbusrb/conclave#44]
Just something I cooked up, thoughts?

![Mockup](http://img.photobucket.com/albums/v472/DeVryGuy/conclave_mockup.png)

**Comment by mdarby** [comment]
Looks good to me :)

**Comment by Bestra** [comment]
I like it.  How'd you make your mockup, btw?

**Comment by DustinFisher** [comment]
I'm guessing this was made with Balsamiq?
http://www.balsamiq.com/products/mockups

Sent from my iPhone

On Sep 24, 2012, at 7:10 PM, Chris Westra notifications@github.com wrote:

I like it. How'd you make your mockup, btw?

—
Reply to this email directly or view it on
GitHubhttps://github.com/columbusrb/conclave/issues/44#issuecomment-8838432.

**Comment by DVG** [comment]
Yup, Balsamiq. Bought a license a couple years ago and haven't regretted it once.

**Comment by skord** [comment]
[comment removed]

**Comment by DVG** [comment]
:)

**Comment by adamalbrecht** [comment]
One thing I dislike about most forum software is the decision to make comments gigantic with tons of un-used white-space and gigantic avatars.  We should try to make the comments leaner so you can see more on a single page.

I think that the Github comments on this page are a pretty good size that uses space efficiently while still being spaced out enough to be readable.

**Comment by mdarby** [comment]
Agreed. Lean and mean is my preference.

**Comment by DVG** [comment]
It's so cool after a fresh pull firing up the server and seeing stuff people have added. I had no idea someone had done the reply/preview tab!
