### ISSUE TITLE
Localize dates/times based on user location

### ISSUE THREAD

**Issue by Bestra** [columbusrb/conclave#55]
Personally I'd like to see dates and times converted from UTC to whatever timezone the user is currently in.  Thoughts?

**Comment by mdarby** [comment]
Yeah, I think that would be nice. ActiveSupport::TimeZone can be a bear though, so I'd like to see a decent amount of tests around it if possible.

**Comment by DVG** [comment]
There's an old but apparently still valid railscast on this http://railscasts.com/episodes/106-time-zones-in-rails-2-1

**Comment by Bestra** [comment]
Yeah, I thought 'easy win!' but after some google searching that's not the case.  We could add a time zone field to our users' information and display based on that.  But that won't apply to visitors.  If the user is simply a visitor, this has to be done client-side, correct?

**Comment by mdarby** [comment]
Very good question. Do we deal with this in JS (whose Date support is frustratingly bad), or just show UTC for non-logged-in users, but even then, that's a pain in the butt. Any thoughts?

**Comment by DVG** [comment]
You could also just display relative time based on when the event occurred (JavaScript based time_ago_in_words like GitHub does) which would be timezone-agnostic

**Comment by mdarby** [comment]
Very true. I think I prefer relative timestamps more, personally.

**Comment by DVG** [comment]
Of course rails can do that by itself, but I seem to remember that it's not the best when there are lots of timestamps on a page. Here's a JavaScript file we would make our own though: https://github.com/wireframe/jquery-relative-timestamp

**Comment by skord** [comment]
I'm partial to http://timeago.yarp.com, which I've used quite a bit before. Javascript time_ago_in_words take UTC and gives back relative time.
