### ISSUE TITLE
Comments need some common-sense validations

### ISSUE THREAD

**Issue by skord** [columbusrb/conclave#58]
Presence, true. Length?

**Comment by mdarby** [comment]
I think presence would be enough?

**Comment by DVG** [comment]
Does postgres have a maximum field length to be concerned about?

**Comment by mdarby** [comment]
According to [stackoverflow](http://stackoverflow.com/questions/10395975/maximum-size-of-text-datatype-in-postgresql), the max would be "whatever fits in 1G"

**Comment by DVG** [comment]
```
class Comment < ActiveRecord::Base
    validates :content, :length => {:maximum => 1073741824}
end
```

**Comment by mdarby** [comment]
Crazy, but technically correct.

**Comment by DVG** [comment]
:)

**Comment by DVG** [comment]
```
#worst_test_ever
visit new_forum_conversation_path(@forum)
txt = ""
while txt.length < 1073741825 do
  txt = "#{txt}1234567890"
end
fill_in "comment_content", with: txt
press_button 'Submit Comment'
page.should have_content "why the hell do you have so much to say"
```

**Comment by tllucero** [comment]
Why is this test taking so long? ;)

**Comment by mdarby** [comment]
As of now, a Comment requires:

```
  validates_presence_of :user, :conversation, :content
```

I think that's sufficient? Thoughts?

**Comment by skord** [comment]
@mdarby See #58. Weird rails-ism I think. When a conversation accepts nested attributes for a comment, I think the validations for the comment validation on :conversation fail because the conversation instance isn't persisted yet. I assume the "right" way, since we've setup the model for accepts_nested_attributes_for, is to actually use the nested attribute feature of simple_form/activerecord, but if you use the :conversation validator, it doesn't work.
