### ISSUE TITLE
Turbolinks breaks Comment Previews

### ISSUE THREAD

**Issue by skord** [columbusrb/conclave#68]
Enabling turbolinks breaks comment previews.

**Comment by skord** [comment]
This is erratic. Sometimes it works, sometimes it doesn't. Steps taken:
1. Click a conversation. 
2. Click quick reply. 
3. Type something into the box
4. Click preview.

Then nothing happens. Tried with Safari and Chrome latest.

**Comment by mdarby** [comment]
Weird. I hate to say I didn't test it, but I bet its that something regarding the previewing is loaded on $(document).ready() -- this works for a full page reload, but turbolinks also listens to 'page:change' for init stuff.

**Comment by skord** [comment]
You put it there, I turned it on. I reverted the commit for the time being, there's some other bugs I need to squash and it's making it difficult. Some sort of strategy on development/production is probably required before re-approaching.
