### ISSUE TITLE
quick replies no longer quick

### ISSUE THREAD

**Issue by skord** [columbusrb/conclave#69]
It seems as though the quick replies are no longer quick replies. Duplicating locally and on heroku. 

![inspector](http://skord.org/i/af84ffe1.png)

Don't know if this is related to the same issue with bootstrap that causes methods to be ignored (why we had to change the signout method to get)

**Comment by mdarby** [comment]
I noticed that this form is AJAX based. After POST the comments/_comment is rendered into the page, but the form isn't cleared. Was this intentional?

Truthfully, I've looked through the JS and can't see how Rails understands where to insert the new comment. What magick is doth?

**Comment by skord** [comment]
I was going to nap but it's all bothering me. 

The form used to clear, it doesn't as of today's commits. 

The new comment is appended to the conversation_comments div per line one of views/comments/create.js.coffee. It's cleared by line #2. Why it's not working completely has to also do with the following.

We're getting bitten elsewhere too, in one place where we already have before, which is twitter/bootstrap#4497. It's not allowing us to use the :remote attribute to AJAX-ify the form, when and how that changed, I'm unsure. I'm not even sure where to point git-blame. 

I just updated my gemfile to use :git => 'git://github.com/seyhunak/twitter-bootstrap-rails.git' for that gem and it's OK, so it's fixed in the latest commits to upstream master but not in the gem yet.
