### ISSUE TITLE
Photo uploads should have EXIF/ITPC stripped

### ISSUE THREAD

**Issue by skord** [columbusrb/conclave#71]
Or should they? Or should we leave it up to the user? EIther way, giving up GPS coordinates without user consent or informing them is pretty dubious.

**Comment by mdarby** [comment]
I'm not sure if this is super important? I mean, I get the privacy concerns, but how difficult is this?

**Comment by rjo1970** [comment]
`mogrify -strip`
does the trick.  Is using rmagick kosher?

**Comment by skord** [comment]
![rubyprof breakdown](http://skord.org/i/a0f8bd0b.png)

I'm still writing benchmarks for all the Ruby image processors I can find, but here's preliminary results. I didn't include rmagick because it was that bad.

_edit_ All benchmarks were 100 runs against a 2MP JPEG. Numbers are seconds it took for the tests to complete.

**edit edit** by "that bad" I meant that memory consumption made the tests bad enough to just choke the machine it was running on.

**Comment by rjo1970** [comment]
point well made

**Comment by rjo1970** [comment]
MiniMagick exposes strip, so:

```
img = MiniMagick::Image.open("ugly_mug.JPG")
img.strip
img.write("ugly_mug_of_unknown_geolocation.JPG")
```

**Comment by skord** [comment]
So I was digging into this this morning and realized Paperclip just uses IM :rage:

You can define a processor to do pretty much anything IM would do. I think this feature has a lot of prerequisites, like working file upload, so I'm going to close it until there's some sort of pressing issue that would force this.

And there will be once people start uploading from their phones :wink:
