### ISSUE TITLE
A user should know about new content

### ISSUE THREAD

**Issue by skord** [columbusrb/conclave#74]
A user should know what they've read and what they haven't

**Comment by dbwest** [comment]
is this useful?
https://github.com/ledermann/unread

**Comment by mdarby** [comment]
Looks pretty neat -- give it a shot!

**Comment by mdarby** [comment]
Working on this now.

**Comment by dbwest** [comment]
I should be at ColumbusRB tonight.

**Comment by mdarby** [comment]
Added in 6d78c5a
