### ISSUE TITLE
Allow uploaded file deletion?

### ISSUE THREAD

**Issue by mdarby** [columbusrb/conclave#85]
So, say I've created a comment with a file upload. Do we allow this photo to be deleted while keeping the comment? Do we allow the photo to be deleted from the Comment#edit screen?

**Comment by rjo1970** [comment]
...when you see the bottom half of the image you just pushed, maybe you want to remove it and keep the comment intact?

**Comment by skord** [comment]
The new widget allows you to edit out any attachments should you chose to.
