### ISSUE TITLE
Clean up terminology in cucumber specs

### ISSUE THREAD

**Issue by mdarby** [columbusrb/conclave#86]
It seems that we have a few different ways of referencing the "conversation page"
- Forum#show page (which it isn't, but should be)
- Comments#index (which is technically correct, but would be cleaner to move logic to Forum#show)

Obviously, I'm for making Forum#show the main page of the app. Thoughts? Any reason to keep it as Comments#index with the matching route?

**Comment by skord** [comment]
The one that gets me is the definition of a reply. I'd vote that a reply is only a reply if the parent_id is set. Otherwise it's just another comment.

**Comment by mdarby** [comment]
I'm back and forth on this as well... If we are doing one flattened list of comments, what is then a "reply". To me, a "reply_id" denotes that we're doing a threaded view.

I vote that we nix the reply_id parent/child altogether and let the user "@" a user (like Github). 

Thoughts?

**Comment by skord** [comment]
My only concern with that is how do you know another user is trying to get your attention? With the parent_id, you could scope comments.my_replies.unread. Either that or trigger the creation of a new object/model called "notification" or something. Say, that's not a terrible idea.

**Comment by mdarby** [comment]
I dig a notification object, but we could easily do a simple highlight on comments that mention the current user's handle too.

**Comment by skord** [comment]
Agreed for the time being. Probably best left for another time anyway. I think that one is going to require some thought.

**Comment by mdarby** [comment]
I moved Comments#index into Conversation#show (I think it makes more sense): 3b5cdaf
