### ISSUE TITLE
A Comment should have file uploads

### ISSUE THREAD

**Issue by mdarby** [columbusrb/conclave#9]
Let's use Paperclip and Amazon's S3 for storage

**Comment by gharraph** [comment]
what would be a good size constrain on the file?

**Comment by mdarby** [comment]
I'd keep it pretty small -- I think this would mostly be used for images. Say 500KB?

**Comment by gharraph** [comment]
alright sounds good

**Comment by gharraph** [comment]
Sorry that I dropped this for couple of days. I had an interview code chalenge that I had to submit today. 
I will resume working on this tonight. I tried to pull the project from the conclave repo, and i found lots of failing tests! is everything currently passing at your end?

**Comment by skord** [comment]
The failures have been on Travis CI's end today. I just ran the specs & features locally and it seems to be OK.

**Comment by gharraph** [comment]
I see Matt already implemented the file upload functionality. Should this issue be closed?

**Comment by mdarby** [comment]
Indeed. :)
