### ISSUE TITLE
Create a read-only API

### ISSUE THREAD

**Issue by skord** [columbusrb/conclave#98]
Create a read only API. Eventually write as well, will require devise tokens.

**Comment by skord** [comment]
Working on this today

**Comment by mdarby** [comment]
Won't `to_json` take care of this?

**Comment by skord** [comment]
Yup. I just don't want to build something else and not have a consistent API available. Say you create a migration that renames a field. Bad news.

**Comment by skord** [comment]
To expound, check https://github.com/skord/conclave/tree/api_wip. Most notably the file in lib and the routes (the tests are f'd, but WIPman).

**Comment by skord** [comment]
I will come back to this someday, there's no general need for it now.
